repos:
  # Pre-commit built ins
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
      args: [--assume-in-merge]
    - id: check-added-large-files

  # GDScript Toolkit
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.4
    hooks:
      - id: gdformat
      - id: gdlint

  # Local repo
  - repo: local
    hooks:
      - id: check-snake-paths
        name: Check snake_case directory and file names
        entry: ./.hooks/check_snake_paths.py
        language: python
        exclude: '^\.github/|src/addons/|README\.md$|LICENSE$|^.pre-commit-config.yaml$'

exclude: '^src/addons/'
