repos:
  # GDScript Toolkit
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.4
    hooks:
      - id: gdlint
      - id: gdformat
        args: [--check, --diff]
exclude: ^src/addons
